// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "sam's diary",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "sam's diary",
            targets: ["AppModule"],
            bundleIdentifier: "co.mariane.sam-s-diary",
            teamIdentifier: "KMNB9J4T55",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeLeft,
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
